Fix bug in getColContentSize when data is an object
"fix" https://github.com/6pac/SlickGrid/issues/688

When the Slick.Grid constructor data is set to a custom object (exposing `getItem(index)` and `getLength()` functions),

The code in `getColContentSize` (https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2468-L2477)

throws `TypeError: rows.slice is not a function` because rows is first set to an object `{ getItem: .., getLength: .. }` and so the following calls to `rows.slice` are invalid.

Note with this PR the function works correctly without throwing, however it is a bit of a kludge as it makes an expensive and unnecessary shallow copy before proceeding . A better solution will change the code below to work directly with `getItem` rather than with `rows[..]`